run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
    skip-tests: true

issues:
  exclude-rules:
    # Exclude complexity issues in test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
        - gocyclo # Explicitly exclude gocyclo for test files

    # Target specifically the test/conformance directory
    - path: test/conformance/
      linters:
        - gocyclo
