server:
  name: "CowGnition RTM"
  port: 8080
  # Optional secret for accessing status endpoint
  status_secret: "change-me-in-production"
  # Development mode enables additional logging and disables certain security checks
  dev_mode: false

rtm:
  api_key: "your_api_key"
  shared_secret: "your_shared_secret"
  # Permission level: read, write, or delete
  permission: "delete"
  # Token refresh interval in hours (default: 24)
  token_refresh: 24

auth:
  token_path: "~/.config/cowgnition/tokens"
  # Disable token encryption for development (not recommended in production)
  disable_encryption: false

logging:
  # Logging level: debug, info, warn, error
  level: "info"
  # Logging format: text or json
  format: "text"
  # Optional log file path (logs to stdout if not specified)
  file: ""
