name: CowGnition CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linters
        run: golangci-lint run

      - name: Run unit tests
        run: go test -v ./test/unit/...

      - name: Run integration tests
        run: go test -v ./test/integration/...

      - name: Run conformance tests
        run: go test -v ./test/conformance/...

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o cowgnition-linux-amd64 ./cmd/server
          GOOS=linux GOARCH=arm64 go build -v -o cowgnition-linux-arm64 ./cmd/server

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -v -o cowgnition-macos-amd64 ./cmd/server
          GOOS=darwin GOARCH=arm64 go build -v -o cowgnition-macos-arm64 ./cmd/server

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o cowgnition-windows-amd64.exe ./cmd/server

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            cowgnition-linux-amd64
            cowgnition-linux-arm64
            cowgnition-macos-amd64
            cowgnition-macos-arm64
            cowgnition-windows-amd64.exe
